import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import IndexMainLogin from '../components/index/IndexMainLogin'

// import 'bootstrap/dist/css/bootstrap.min.css';
// import { Card, CardText, CardHeader, CardBody, Button } from 'reactstrap';

import IndexMainFooter from '../components/index/IndexMainFooter'

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  return (
    <>
      <Head>
        <title>Войти в Систему</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Создавай юридические документы на лету...&nbsp;
            {/* <code className={styles.code}>pages/index.js</code> */}
          </p>
          <div>
            <a
              href="/"
              target="_self"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/svg-ooo-fdt-image.svg"
                alt="ООО ФДТ"
                className={styles.vercelLogo}
                width={120}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          {/* Здесь необходимо сделать форму Логина */}
          <IndexMainLogin />
        </div>

        <IndexMainFooter />
      </main>
    </>
  )
}
